@startuml
skinparam linetype ortho

node "Frontend" {
  component Client [
    Frontend
    React TS
  ]
}

node "Backend" {
  component APIGateway [
    API Gateway
  ]
  component Authentification [
    Authentification
  ]
  component Authorization [
    Authorization
  ]

  component APIUsers [
    API Users & Roles
  ]
  component APIBusiness [
    API Business
  ]

  database "PostgreSQL"
  database "MongoDB"

  port API
  API -- [APIGateway]

  [APIGateway] -- [Authentification]
  [APIGateway] -- [Authorization]
  [Authentification] -- [APIUsers]
  [Authorization] -- [APIUsers]

  [APIGateway] -- [APIBusiness]

  [APIUsers] -- [PostgreSQL]
  [APIBusiness] -- [MongoDB]
}

Client -- [API]
@enduml